"""create_step2_schema

Revision ID: 71f1d55cea91
Revises:
Create Date: 2026-09-29 18:42:39.075699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71f1d55cea91"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("estimated_hours", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.create_table(
        "mock_tests",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("passing_percentage", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="mockteststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mock_tests_difficulty"), "mock_tests", ["difficulty"], unique=False
    )
    op.create_index(op.f("ix_mock_tests_id"), "mock_tests", ["id"], unique=False)
    op.create_index(op.f("ix_mock_tests_slug"), "mock_tests", ["slug"], unique=True)
    op.create_index(
        op.f("ix_mock_tests_status"), "mock_tests", ["status"], unique=False
    )
    op.create_table(
        "question_tags",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_question_tags_id"), "question_tags", ["id"], unique=False)
    op.create_index(
        op.f("ix_question_tags_name"), "question_tags", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_question_tags_slug"), "question_tags", ["slug"], unique=True
    )
    op.create_table(
        "test_blueprints",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_blueprints_id"), "test_blueprints", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_test_blueprints_slug"), "test_blueprints", ["slug"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("current_level", sa.String(length=32), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "STUDENT",
                "INSTRUCTOR",
                "ADMIN",
                name="userrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "mock_test_attempts",
        sa.Column("mock_test_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "SUBMITTED",
                "EXPIRED",
                "ABANDONED",
                name="attemptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mock_test_id"], ["mock_tests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mock_test_attempts_id"), "mock_test_attempts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_mock_test_attempts_mock_test_id"),
        "mock_test_attempts",
        ["mock_test_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_test_attempts_status"),
        "mock_test_attempts",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_test_attempts_user_id"),
        "mock_test_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "modules",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "slug", name="uq_module_course_slug"),
    )
    op.create_index(
        op.f("ix_modules_course_id"), "modules", ["course_id"], unique=False
    )
    op.create_index(op.f("ix_modules_id"), "modules", ["id"], unique=False)
    op.create_index(op.f("ix_modules_slug"), "modules", ["slug"], unique=False)
    op.create_table(
        "test_results",
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("incorrect_answers", sa.Integer(), nullable=False),
        sa.Column("unanswered", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["mock_test_attempts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(op.f("ix_test_results_id"), "test_results", ["id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module_id", "slug", name="uq_topic_module_slug"),
    )
    op.create_index(
        op.f("ix_topics_difficulty"), "topics", ["difficulty"], unique=False
    )
    op.create_index(op.f("ix_topics_id"), "topics", ["id"], unique=False)
    op.create_index(op.f("ix_topics_module_id"), "topics", ["module_id"], unique=False)
    op.create_index(op.f("ix_topics_slug"), "topics", ["slug"], unique=False)
    op.create_table(
        "labs",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=True),
        sa.Column("prerequisites", sa.Text(), nullable=True),
        sa.Column("environment_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="labstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id", "slug", name="uq_lab_topic_slug"),
    )
    op.create_index(op.f("ix_labs_difficulty"), "labs", ["difficulty"], unique=False)
    op.create_index(op.f("ix_labs_id"), "labs", ["id"], unique=False)
    op.create_index(op.f("ix_labs_slug"), "labs", ["slug"], unique=False)
    op.create_index(op.f("ix_labs_topic_id"), "labs", ["topic_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "LESSON",
                "ARTICLE",
                "DIAGRAM",
                "EXAMPLE",
                "REFERENCE",
                name="contenttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id", "slug", name="uq_lesson_topic_slug"),
    )
    op.create_index(op.f("ix_lessons_id"), "lessons", ["id"], unique=False)
    op.create_index(op.f("ix_lessons_slug"), "lessons", ["slug"], unique=False)
    op.create_index(op.f("ix_lessons_topic_id"), "lessons", ["topic_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SINGLE_CHOICE",
                "MULTIPLE_CHOICE",
                "TRUE_FALSE",
                "FILL_BLANK",
                "NUMERICAL",
                "SUBNETTING",
                "SCENARIO",
                "PACKET_ANALYSIS",
                "MATCHING",
                name="questiontype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "cognitive_level",
            sa.Enum(
                "REMEMBER",
                "UNDERSTAND",
                "APPLY",
                "ANALYZE",
                name="cognitivelevel",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("learning_objective", sa.Text(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("estimated_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW",
                "PUBLISHED",
                "ARCHIVED",
                name="questionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_difficulty"), "questions", ["difficulty"], unique=False
    )
    op.create_index(op.f("ix_questions_id"), "questions", ["id"], unique=False)
    op.create_index(
        op.f("ix_questions_question_type"), "questions", ["question_type"], unique=False
    )
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_index(
        op.f("ix_questions_topic_id"), "questions", ["topic_id"], unique=False
    )
    op.create_table(
        "test_blueprint_topics",
        sa.Column("blueprint_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficultylevel",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SINGLE_CHOICE",
                "MULTIPLE_CHOICE",
                "TRUE_FALSE",
                "FILL_BLANK",
                "NUMERICAL",
                "SUBNETTING",
                "SCENARIO",
                "PACKET_ANALYSIS",
                "MATCHING",
                name="questiontype",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column(
            "cognitive_level",
            sa.Enum(
                "REMEMBER",
                "UNDERSTAND",
                "APPLY",
                "ANALYZE",
                name="cognitivelevel",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blueprint_id"], ["test_blueprints.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_blueprint_topics_blueprint_id"),
        "test_blueprint_topics",
        ["blueprint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_blueprint_topics_id"),
        "test_blueprint_topics",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_blueprint_topics_topic_id"),
        "test_blueprint_topics",
        ["topic_id"],
        unique=False,
    )
    op.create_table(
        "topic_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="progressstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("completion_percentage", sa.Float(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "topic_id", name="uq_user_topic_progress"),
    )
    op.create_index(
        op.f("ix_topic_progress_id"), "topic_progress", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_progress_topic_id"), "topic_progress", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_progress_user_id"), "topic_progress", ["user_id"], unique=False
    )
    op.create_table(
        "lab_attempts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lab_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "SUBMITTED",
                "EXPIRED",
                "ABANDONED",
                name="attemptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lab_attempts_id"), "lab_attempts", ["id"], unique=False)
    op.create_index(
        op.f("ix_lab_attempts_lab_id"), "lab_attempts", ["lab_id"], unique=False
    )
    op.create_index(
        op.f("ix_lab_attempts_user_id"), "lab_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "lab_questions",
        sa.Column("lab_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SINGLE_CHOICE",
                "MULTIPLE_CHOICE",
                "TRUE_FALSE",
                "FILL_BLANK",
                "NUMERICAL",
                "SUBNETTING",
                "SCENARIO",
                "PACKET_ANALYSIS",
                "MATCHING",
                name="questiontype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("answer_data", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lab_questions_id"), "lab_questions", ["id"], unique=False)
    op.create_index(
        op.f("ix_lab_questions_lab_id"), "lab_questions", ["lab_id"], unique=False
    )
    op.create_table(
        "lab_steps",
        sa.Column("lab_id", sa.Integer(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("expected_observation", sa.Text(), nullable=True),
        sa.Column("validation_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lab_id"], ["labs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lab_id", "step_number", name="uq_lab_step_number"),
    )
    op.create_index(op.f("ix_lab_steps_id"), "lab_steps", ["id"], unique=False)
    op.create_index(op.f("ix_lab_steps_lab_id"), "lab_steps", ["lab_id"], unique=False)
    op.create_table(
        "lesson_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="progressstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_user_lesson_progress"),
    )
    op.create_index(
        op.f("ix_lesson_progress_id"), "lesson_progress", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_progress_lesson_id"),
        "lesson_progress",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_progress_user_id"), "lesson_progress", ["user_id"], unique=False
    )
    op.create_table(
        "mock_test_questions",
        sa.Column("mock_test_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mock_test_id"], ["mock_tests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mock_test_id", "question_id", name="uq_mock_test_question"
        ),
    )
    op.create_index(
        op.f("ix_mock_test_questions_id"), "mock_test_questions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_mock_test_questions_mock_test_id"),
        "mock_test_questions",
        ["mock_test_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_test_questions_question_id"),
        "mock_test_questions",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "question_options",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_options_id"), "question_options", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_question_options_question_id"),
        "question_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "question_tags_association",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["question_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("question_id", "tag_id"),
    )
    op.create_table(
        "student_answers",
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("answer_data", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["mock_test_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name="uq_attempt_question_answer"
        ),
    )
    op.create_index(
        op.f("ix_student_answers_attempt_id"),
        "student_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_answers_id"), "student_answers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_student_answers_question_id"),
        "student_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_answers_question_id"), table_name="student_answers")
    op.drop_index(op.f("ix_student_answers_id"), table_name="student_answers")
    op.drop_index(op.f("ix_student_answers_attempt_id"), table_name="student_answers")
    op.drop_table("student_answers")
    op.drop_table("question_tags_association")
    op.drop_index(
        op.f("ix_question_options_question_id"), table_name="question_options"
    )
    op.drop_index(op.f("ix_question_options_id"), table_name="question_options")
    op.drop_table("question_options")
    op.drop_index(
        op.f("ix_mock_test_questions_question_id"), table_name="mock_test_questions"
    )
    op.drop_index(
        op.f("ix_mock_test_questions_mock_test_id"), table_name="mock_test_questions"
    )
    op.drop_index(op.f("ix_mock_test_questions_id"), table_name="mock_test_questions")
    op.drop_table("mock_test_questions")
    op.drop_index(op.f("ix_lesson_progress_user_id"), table_name="lesson_progress")
    op.drop_index(op.f("ix_lesson_progress_lesson_id"), table_name="lesson_progress")
    op.drop_index(op.f("ix_lesson_progress_id"), table_name="lesson_progress")
    op.drop_table("lesson_progress")
    op.drop_index(op.f("ix_lab_steps_lab_id"), table_name="lab_steps")
    op.drop_index(op.f("ix_lab_steps_id"), table_name="lab_steps")
    op.drop_table("lab_steps")
    op.drop_index(op.f("ix_lab_questions_lab_id"), table_name="lab_questions")
    op.drop_index(op.f("ix_lab_questions_id"), table_name="lab_questions")
    op.drop_table("lab_questions")
    op.drop_index(op.f("ix_lab_attempts_user_id"), table_name="lab_attempts")
    op.drop_index(op.f("ix_lab_attempts_lab_id"), table_name="lab_attempts")
    op.drop_index(op.f("ix_lab_attempts_id"), table_name="lab_attempts")
    op.drop_table("lab_attempts")
    op.drop_index(op.f("ix_topic_progress_user_id"), table_name="topic_progress")
    op.drop_index(op.f("ix_topic_progress_topic_id"), table_name="topic_progress")
    op.drop_index(op.f("ix_topic_progress_id"), table_name="topic_progress")
    op.drop_table("topic_progress")
    op.drop_index(
        op.f("ix_test_blueprint_topics_topic_id"), table_name="test_blueprint_topics"
    )
    op.drop_index(
        op.f("ix_test_blueprint_topics_id"), table_name="test_blueprint_topics"
    )
    op.drop_index(
        op.f("ix_test_blueprint_topics_blueprint_id"),
        table_name="test_blueprint_topics",
    )
    op.drop_table("test_blueprint_topics")
    op.drop_index(op.f("ix_questions_topic_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_question_type"), table_name="questions")
    op.drop_index(op.f("ix_questions_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_difficulty"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_lessons_topic_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_slug"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_labs_topic_id"), table_name="labs")
    op.drop_index(op.f("ix_labs_slug"), table_name="labs")
    op.drop_index(op.f("ix_labs_id"), table_name="labs")
    op.drop_index(op.f("ix_labs_difficulty"), table_name="labs")
    op.drop_table("labs")
    op.drop_index(op.f("ix_topics_slug"), table_name="topics")
    op.drop_index(op.f("ix_topics_module_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_difficulty"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_test_results_id"), table_name="test_results")
    op.drop_table("test_results")
    op.drop_index(op.f("ix_modules_slug"), table_name="modules")
    op.drop_index(op.f("ix_modules_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_course_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(
        op.f("ix_mock_test_attempts_user_id"), table_name="mock_test_attempts"
    )
    op.drop_index(op.f("ix_mock_test_attempts_status"), table_name="mock_test_attempts")
    op.drop_index(
        op.f("ix_mock_test_attempts_mock_test_id"), table_name="mock_test_attempts"
    )
    op.drop_index(op.f("ix_mock_test_attempts_id"), table_name="mock_test_attempts")
    op.drop_table("mock_test_attempts")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_test_blueprints_slug"), table_name="test_blueprints")
    op.drop_index(op.f("ix_test_blueprints_id"), table_name="test_blueprints")
    op.drop_table("test_blueprints")
    op.drop_index(op.f("ix_question_tags_slug"), table_name="question_tags")
    op.drop_index(op.f("ix_question_tags_name"), table_name="question_tags")
    op.drop_index(op.f("ix_question_tags_id"), table_name="question_tags")
    op.drop_table("question_tags")
    op.drop_index(op.f("ix_mock_tests_status"), table_name="mock_tests")
    op.drop_index(op.f("ix_mock_tests_slug"), table_name="mock_tests")
    op.drop_index(op.f("ix_mock_tests_id"), table_name="mock_tests")
    op.drop_index(op.f("ix_mock_tests_difficulty"), table_name="mock_tests")
    op.drop_table("mock_tests")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
