"""step_17_incident_response_case_management_mitre

Revision ID: 71031b25909d
Revises: i01e2f345683
Create Date: 2026-10-01 06:16:32.027064

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71031b25909d'
down_revision: str | None = 'i01e2f345683'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_tactics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tactic_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_tactics_id'), 'attack_tactics', ['id'], unique=False)
    op.create_index(op.f('ix_attack_tactics_tactic_id'), 'attack_tactics', ['tactic_id'], unique=True)
    op.create_table('incident_playbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity_guidance', sa.String(length=20), nullable=False),
    sa.Column('primary_tactic_id', sa.String(length=20), nullable=True),
    sa.Column('phases_definition', sa.Text(), nullable=False),
    sa.Column('checklist_json', sa.Text(), nullable=False),
    sa.Column('recommended_actions_json', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_playbooks_category'), 'incident_playbooks', ['category'], unique=False)
    op.create_index(op.f('ix_incident_playbooks_id'), 'incident_playbooks', ['id'], unique=False)
    op.create_index(op.f('ix_incident_playbooks_playbook_id'), 'incident_playbooks', ['playbook_id'], unique=True)
    op.create_table('attack_techniques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('tactic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detection_guidance', sa.Text(), nullable=True),
    sa.Column('mitigation_guidance', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=20), nullable=True),
    sa.Column('platforms', sa.String(length=200), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['attack_tactics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_techniques_id'), 'attack_techniques', ['id'], unique=False)
    op.create_index(op.f('ix_attack_techniques_parent_technique_id'), 'attack_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_attack_techniques_tactic_id'), 'attack_techniques', ['tactic_id'], unique=False)
    op.create_index(op.f('ix_attack_techniques_technique_id'), 'attack_techniques', ['technique_id'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('lead_analyst', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eradicated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('simulation_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_id'], ['incident_playbooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assigned_to_id'), 'incidents', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_incidents_case_id'), 'incidents', ['case_id'], unique=False)
    op.create_index(op.f('ix_incidents_classification'), 'incidents', ['classification'], unique=False)
    op.create_index(op.f('ix_incidents_created_by_id'), 'incidents', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_phase'), 'incidents', ['phase'], unique=False)
    op.create_index(op.f('ix_incidents_playbook_id'), 'incidents', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('source_engine', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('relevance', sa.String(length=30), nullable=False),
    sa.Column('is_contained', sa.Boolean(), nullable=False),
    sa.Column('collected_by_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_collected_by_id'), 'incident_evidence', ['collected_by_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_evidence_id'), 'incident_evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_incident_evidence_evidence_type'), 'incident_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_incident_evidence_id'), 'incident_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_source_engine'), 'incident_evidence', ['source_engine'], unique=False)
    op.create_index(op.f('ix_incident_evidence_source_id'), 'incident_evidence', ['source_id'], unique=False)
    op.create_table('incident_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('affected_systems', sa.Text(), nullable=True),
    sa.Column('affected_accounts', sa.Text(), nullable=True),
    sa.Column('indicators_observed', sa.Text(), nullable=True),
    sa.Column('mitre_technique', sa.String(length=50), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_findings_created_by_id'), 'incident_findings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_incident_findings_finding_id'), 'incident_findings', ['finding_id'], unique=False)
    op.create_index(op.f('ix_incident_findings_id'), 'incident_findings', ['id'], unique=False)
    op.create_index(op.f('ix_incident_findings_incident_id'), 'incident_findings', ['incident_id'], unique=False)
    op.create_table('incident_hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_hypotheses_created_by_id'), 'incident_hypotheses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_incident_hypotheses_hypothesis_id'), 'incident_hypotheses', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_incident_hypotheses_id'), 'incident_hypotheses', ['id'], unique=False)
    op.create_index(op.f('ix_incident_hypotheses_incident_id'), 'incident_hypotheses', ['incident_id'], unique=False)
    op.create_table('incident_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_notes_id'), 'incident_notes', ['id'], unique=False)
    op.create_index(op.f('ix_incident_notes_incident_id'), 'incident_notes', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_notes_user_id'), 'incident_notes', ['user_id'], unique=False)
    op.create_table('incident_response_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_identifier', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('simulation_only', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('simulated_outcome', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_response_actions_action_id'), 'incident_response_actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_incident_response_actions_action_type'), 'incident_response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_incident_response_actions_category'), 'incident_response_actions', ['category'], unique=False)
    op.create_index(op.f('ix_incident_response_actions_executed_by_id'), 'incident_response_actions', ['executed_by_id'], unique=False)
    op.create_index(op.f('ix_incident_response_actions_id'), 'incident_response_actions', ['id'], unique=False)
    op.create_index(op.f('ix_incident_response_actions_incident_id'), 'incident_response_actions', ['incident_id'], unique=False)
    op.create_table('incident_technique_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('mapping_confidence', sa.String(length=30), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('mapped_by_id', sa.Integer(), nullable=True),
    sa.Column('mapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technique_id'], ['attack_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_technique_mappings_id'), 'incident_technique_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_incident_technique_mappings_incident_id'), 'incident_technique_mappings', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_technique_mappings_mapped_by_id'), 'incident_technique_mappings', ['mapped_by_id'], unique=False)
    op.create_index(op.f('ix_incident_technique_mappings_technique_id'), 'incident_technique_mappings', ['technique_id'], unique=False)
    op.create_table('incident_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=20), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_events_created_by_id'), 'incident_timeline_events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_event_category'), 'incident_timeline_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_id'), 'incident_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_incident_id'), 'incident_timeline_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_mitre_technique_id'), 'incident_timeline_events', ['mitre_technique_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_events_timestamp'), 'incident_timeline_events', ['timestamp'], unique=False)
    op.create_table('evidence_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['incident_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_audit_logs_evidence_id'), 'evidence_audit_logs', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_audit_logs_id'), 'evidence_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_audit_logs_user_id'), 'evidence_audit_logs', ['user_id'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['detection_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_alerts_alert_id'), 'incident_alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incident_alerts_id'), 'incident_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_incident_alerts_incident_id'), 'incident_alerts', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_alerts_incident_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_alert_id'), table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_index(op.f('ix_evidence_audit_logs_user_id'), table_name='evidence_audit_logs')
    op.drop_index(op.f('ix_evidence_audit_logs_id'), table_name='evidence_audit_logs')
    op.drop_index(op.f('ix_evidence_audit_logs_evidence_id'), table_name='evidence_audit_logs')
    op.drop_table('evidence_audit_logs')
    op.alter_column('indicator_timelines', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_indicator_relationships_target_indicator_id'), table_name='indicator_relationships')
    op.drop_index(op.f('ix_indicator_relationships_source_indicator_id'), table_name='indicator_relationships')
    op.create_index(op.f('ix_indicator_relationships_target_id'), 'indicator_relationships', ['target_indicator_id'], unique=False)
    op.create_index(op.f('ix_indicator_relationships_source_id'), 'indicator_relationships', ['source_indicator_id'], unique=False)
    op.alter_column('indicator_relationships', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('indicator_observations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('indicator_notes', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('indicator_notes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_hunt_events_event_id'), table_name='hunt_events')
    op.create_index(op.f('ix_hunt_events_event_id'), 'hunt_events', ['event_id'], unique=False)
    op.drop_index(op.f('ix_hunt_datasets_dataset_id'), table_name='hunt_datasets')
    op.create_index(op.f('ix_hunt_datasets_dataset_id'), 'hunt_datasets', ['dataset_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_scenarios_slug'), table_name='endpoint_scenarios')
    op.create_index(op.f('ix_endpoint_scenarios_slug'), 'endpoint_scenarios', ['slug'], unique=False)
    op.drop_index(op.f('ix_endpoint_scenarios_scenario_id'), table_name='endpoint_scenarios')
    op.create_index(op.f('ix_endpoint_scenarios_scenario_id'), 'endpoint_scenarios', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_investigations_stable_id'), table_name='endpoint_investigations')
    op.create_index(op.f('ix_endpoint_investigations_stable_id'), 'endpoint_investigations', ['stable_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_hosts_stable_id'), table_name='endpoint_hosts')
    op.create_index(op.f('ix_endpoint_hosts_stable_id'), 'endpoint_hosts', ['stable_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_hosts_hostname'), table_name='endpoint_hosts')
    op.create_index(op.f('ix_endpoint_hosts_hostname'), 'endpoint_hosts', ['hostname'], unique=False)
    op.drop_index(op.f('ix_endpoint_events_source_port'), table_name='endpoint_events')
    op.drop_index(op.f('ix_endpoint_events_event_id'), table_name='endpoint_events')
    op.create_index(op.f('ix_endpoint_events_event_id'), 'endpoint_events', ['event_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_conclusions_investigation_id'), table_name='endpoint_conclusions')
    op.create_index(op.f('ix_endpoint_conclusions_investigation_id'), 'endpoint_conclusions', ['investigation_id'], unique=False)
    op.drop_index(op.f('ix_correlation_alerts_alert_id'), table_name='correlation_alerts')
    op.create_index(op.f('ix_correlation_alerts_alert_id'), 'correlation_alerts', ['alert_id'], unique=False)
    op.drop_index(op.f('ix_incident_alerts_incident_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_id'), table_name='incident_alerts')
    op.drop_index(op.f('ix_incident_alerts_alert_id'), table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_index(op.f('ix_evidence_audit_logs_user_id'), table_name='evidence_audit_logs')
    op.drop_index(op.f('ix_evidence_audit_logs_id'), table_name='evidence_audit_logs')
    op.drop_index(op.f('ix_evidence_audit_logs_evidence_id'), table_name='evidence_audit_logs')
    op.drop_table('evidence_audit_logs')
    op.drop_index(op.f('ix_incident_timeline_events_timestamp'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_mitre_technique_id'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_incident_id'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_id'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_event_category'), table_name='incident_timeline_events')
    op.drop_index(op.f('ix_incident_timeline_events_created_by_id'), table_name='incident_timeline_events')
    op.drop_table('incident_timeline_events')
    op.drop_index(op.f('ix_incident_technique_mappings_technique_id'), table_name='incident_technique_mappings')
    op.drop_index(op.f('ix_incident_technique_mappings_mapped_by_id'), table_name='incident_technique_mappings')
    op.drop_index(op.f('ix_incident_technique_mappings_incident_id'), table_name='incident_technique_mappings')
    op.drop_index(op.f('ix_incident_technique_mappings_id'), table_name='incident_technique_mappings')
    op.drop_table('incident_technique_mappings')
    op.drop_index(op.f('ix_incident_response_actions_incident_id'), table_name='incident_response_actions')
    op.drop_index(op.f('ix_incident_response_actions_id'), table_name='incident_response_actions')
    op.drop_index(op.f('ix_incident_response_actions_executed_by_id'), table_name='incident_response_actions')
    op.drop_index(op.f('ix_incident_response_actions_category'), table_name='incident_response_actions')
    op.drop_index(op.f('ix_incident_response_actions_action_type'), table_name='incident_response_actions')
    op.drop_index(op.f('ix_incident_response_actions_action_id'), table_name='incident_response_actions')
    op.drop_table('incident_response_actions')
    op.drop_index(op.f('ix_incident_notes_user_id'), table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_incident_id'), table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_id'), table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_index(op.f('ix_incident_hypotheses_incident_id'), table_name='incident_hypotheses')
    op.drop_index(op.f('ix_incident_hypotheses_id'), table_name='incident_hypotheses')
    op.drop_index(op.f('ix_incident_hypotheses_hypothesis_id'), table_name='incident_hypotheses')
    op.drop_index(op.f('ix_incident_hypotheses_created_by_id'), table_name='incident_hypotheses')
    op.drop_table('incident_hypotheses')
    op.drop_index(op.f('ix_incident_findings_incident_id'), table_name='incident_findings')
    op.drop_index(op.f('ix_incident_findings_id'), table_name='incident_findings')
    op.drop_index(op.f('ix_incident_findings_finding_id'), table_name='incident_findings')
    op.drop_index(op.f('ix_incident_findings_created_by_id'), table_name='incident_findings')
    op.drop_table('incident_findings')
    op.drop_index(op.f('ix_incident_evidence_source_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_source_engine'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_evidence_type'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_evidence_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_collected_by_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_playbook_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_phase'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_by_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_classification'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_case_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_to_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_attack_techniques_technique_id'), table_name='attack_techniques')
    op.drop_index(op.f('ix_attack_techniques_tactic_id'), table_name='attack_techniques')
    op.drop_index(op.f('ix_attack_techniques_parent_technique_id'), table_name='attack_techniques')
    op.drop_index(op.f('ix_attack_techniques_id'), table_name='attack_techniques')
    op.drop_table('attack_techniques')
    op.drop_index(op.f('ix_incident_playbooks_playbook_id'), table_name='incident_playbooks')
    op.drop_index(op.f('ix_incident_playbooks_id'), table_name='incident_playbooks')
    op.drop_index(op.f('ix_incident_playbooks_category'), table_name='incident_playbooks')
    op.drop_table('incident_playbooks')
    op.drop_index(op.f('ix_attack_tactics_tactic_id'), table_name='attack_tactics')
    op.drop_index(op.f('ix_attack_tactics_id'), table_name='attack_tactics')
    op.drop_table('attack_tactics')
    # ### end Alembic commands ###
