"""add_step3_prerequisites_bookmarks_tracking

Revision ID: 749a1792479c
Revises: 71f1d55cea91
Create Date: 2026-09-29 19:17:09.692887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "749a1792479c"
down_revision: str | None = "71f1d55cea91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_prerequisites",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["prerequisite_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topic_id", "prerequisite_id"),
    )
    op.create_table(
        "lesson_bookmarks",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_user_lesson_bookmark"),
    )
    op.create_index(
        op.f("ix_lesson_bookmarks_id"), "lesson_bookmarks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_bookmarks_lesson_id"),
        "lesson_bookmarks",
        ["lesson_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_bookmarks_user_id"),
        "lesson_bookmarks",
        ["user_id"],
        unique=False,
    )

    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True)
        )

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "estimated_minutes", sa.Integer(), server_default="30", nullable=False
            )
        )
        batch_op.add_column(sa.Column("learning_objectives", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("security_relevance", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_column("security_relevance")
        batch_op.drop_column("learning_objectives")
        batch_op.drop_column("estimated_minutes")

    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.drop_column("last_accessed_at")
        batch_op.drop_column("started_at")

    op.drop_index(op.f("ix_lesson_bookmarks_user_id"), table_name="lesson_bookmarks")
    op.drop_index(op.f("ix_lesson_bookmarks_lesson_id"), table_name="lesson_bookmarks")
    op.drop_index(op.f("ix_lesson_bookmarks_id"), table_name="lesson_bookmarks")
    op.drop_table("lesson_bookmarks")
    op.drop_table("topic_prerequisites")
    # ### end Alembic commands ###
