import '@testing-library/jest-dom'
import { render, screen, act } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'

import { IncidentsPage } from '../pages/Soc/IncidentsPage'
import { IncidentDetailPage } from '../pages/Soc/IncidentDetailPage'
import { MitreCoveragePage } from '../pages/Soc/MitreCoveragePage'
import { PlaybooksPage } from '../pages/Soc/PlaybooksPage'
import { incidentResponseApi } from '../services/incidentResponseApi'
import type {
  AttackTactic,
  AttackTechnique,
  Incident,
  IncidentEvidence,
  IncidentFinding,
  IncidentHypothesis,
  IncidentMetrics,
  IncidentPlaybook,
  IncidentReport,
  IncidentTimelineEvent,
  MatrixCoverageResponse,
  ResponseAction,
} from '../types/incidentResponse'

vi.mock('../services/incidentResponseApi', () => ({
  incidentResponseApi: {
    listIncidents: vi.fn(),
    getIncident: vi.fn(),
    createIncident: vi.fn(),
    updateIncident: vi.fn(),
    getMetrics: vi.fn(),
    escalateAlert: vi.fn(),
    addEvidence: vi.fn(),
    verifyEvidenceHash: vi.fn(),
    updateEvidence: vi.fn(),
    listTimeline: vi.fn(),
    addTimelineEvent: vi.fn(),
    syncTimeline: vi.fn(),
    createHypothesis: vi.fn(),
    updateHypothesis: vi.fn(),
    recordFinding: vi.fn(),
    listActions: vi.fn(),
    proposeAction: vi.fn(),
    executeAction: vi.fn(),
    revertAction: vi.fn(),
    listTactics: vi.fn(),
    listTechniques: vi.fn(),
    getMatrixCoverage: vi.fn(),
    mapTechnique: vi.fn(),
    unmapTechnique: vi.fn(),
    listPlaybooks: vi.fn(),
    getPlaybook: vi.fn(),
    attachPlaybook: vi.fn(),
    getIncidentReport: vi.fn(),
    addNote: vi.fn(),
  },
}))

describe('Step 17: Incident Response, Case Management & MITRE ATT&CK Framework', () => {
  const mockMetrics: IncidentMetrics = {
    total_incidents: 6,
    active_incidents: 4,
    closed_incidents: 2,
    by_status: { INVESTIGATING: 2, CONTAINMENT: 1, NEW: 1, RESOLVED: 2 },
    by_severity: { CRITICAL: 2, HIGH: 2, MEDIUM: 1, LOW: 1 },
    by_type: { ENDPOINT_COMPROMISE: 2, MALWARE_INDICATOR: 2, SUSPICIOUS_LOGIN: 2 },
  }

  const mockEvidence: IncidentEvidence[] = [
    {
      id: 101,
      evidence_id: 'EVD-ALT-001-A1',
      incident_id: 1,
      title: 'Suspicious PowerShell Execution Alert',
      description: 'Alert generated by Sysmon Process Create Rule 101',
      evidence_type: 'ALERT',
      source_engine: 'DETECTION',
      source_id: 'ALT-101',
      source_ref: 'sysmon_rules.yaml:rule_101',
      hash_sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      relevance: 'SUPPORTING',
      is_contained: false,
      collected_at: '2026-10-01T00:05:00Z',
      data_payload: JSON.stringify({ process_name: 'powershell.exe', pid: 4892 }),
      audit_logs: [
        {
          id: 1,
          evidence_id: 101,
          action: 'ATTACHED',
          details: 'Automated ingestion from Detection alert ALT-101',
          timestamp: '2026-10-01T00:05:00Z',
        },
      ],
    },
  ]

  const mockTimeline: IncidentTimelineEvent[] = [
    {
      id: 201,
      incident_id: 1,
      timestamp: '2026-10-01T00:01:00Z',
      title: 'Initial Malicious Execution',
      description: 'Obfuscated PowerShell script started via scheduled task.',
      event_category: 'EXECUTION',
      source: 'ENDPOINT',
      source_id: 'HOST-001',
      mitre_technique_id: 'T1059.001',
      is_milestone: true,
    },
  ]

  const mockHypotheses: IncidentHypothesis[] = [
    {
      id: 301,
      hypothesis_id: 'HYP-001',
      incident_id: 1,
      statement: 'Attacker gained initial access via compromised SSH key.',
      status: 'SUPPORTED',
      confidence: 'HIGH',
      rationale: 'Observed matching SSH logs in SIEM.',
    },
  ]

  const mockFindings: IncidentFinding[] = [
    {
      id: 401,
      finding_id: 'FND-001',
      incident_id: 1,
      title: 'PowerShell Memory Injection Confirmed',
      description: 'Analyzed process memory dumps confirm payload reflection.',
      severity: 'CRITICAL',
      mitre_technique: 'T1055',
    },
  ]

  const mockActions: ResponseAction[] = [
    {
      id: 501,
      action_id: 'ACT-001',
      incident_id: 1,
      action_type: 'SIMULATE_HOST_ISOLATION',
      category: 'CONTAINMENT',
      target_type: 'HOST',
      target_identifier: 'NN-DEV-001',
      status: 'PROPOSED',
      reason: 'Isolating the endpoint stops lateral traversal while preserving forensic memory state.',
      risk_assessment: 'Medium risk of interrupting legitimate dev tasks.',
      expected_impact: 'Network connectivity severed for host NN-DEV-001.',
      simulation_only: true,
    },
  ]

  const mockIncidents: Incident[] = [
    {
      id: 1,
      incident_id: 'INC-2026-0001',
      title: 'PowerShell Memory Injection & Lateral Reconnaissance',
      description: 'Suspicious obfuscated PowerShell executed on developer workstation.',
      incident_type: 'ENDPOINT_COMPROMISE',
      severity: 'CRITICAL',
      priority: 'P1',
      status: 'INVESTIGATING',
      classification: 'CONFIRMED_INCIDENT',
      phase: 'DETECTION_ANALYSIS',
      lead_analyst: 'SOC Lead Analyst',
      detected_at: '2026-10-01T00:00:00Z',
      simulation_mode: true,
      summary: 'Suspicious obfuscated PowerShell executed on developer workstation.',
      impact_assessment: 'Developer workstation isolated.',
      root_cause: 'Compromised SSH credentials.',
      lessons_learned: 'Enforce MFA and certificate-based auth.',
      recommendations: 'Rotate developer keys immediately.',
      evidence: mockEvidence,
      timeline_events: mockTimeline,
      hypotheses: mockHypotheses,
      findings: mockFindings,
      response_actions: mockActions,
      technique_mappings: [],
    },
    {
      id: 2,
      incident_id: 'INC-2026-0002',
      title: 'DGA DNS Beaconing & Exfiltration Attempt',
      description: 'High volume DNS queries toward suspicious pseudo-random domains.',
      incident_type: 'DNS_ANOMALY',
      severity: 'HIGH',
      priority: 'P2',
      status: 'CONTAINMENT',
      classification: 'CONFIRMED_INCIDENT',
      phase: 'CONTAINMENT_ERADICATION_RECOVERY',
      lead_analyst: 'Tier 1 Analyst',
      detected_at: '2026-10-01T00:30:00Z',
      simulation_mode: true,
    },
  ]

  const mockTactics: AttackTactic[] = [
    {
      id: 1,
      tactic_id: 'TA0001',
      name: 'Initial Access',
      description: 'The adversary is trying to get into your network.',
      display_order: 1,
      techniques: [
        {
          id: 11,
          technique_id: 'T1190',
          tactic_id: 1,
          name: 'Exploit Public-Facing Application',
          description: 'Adversaries may attempt to exploit vulnerabilities.',
          is_subtechnique: false,
        },
      ],
    },
    {
      id: 2,
      tactic_id: 'TA0002',
      name: 'Execution',
      description: 'The adversary is trying to run malicious code.',
      display_order: 2,
      techniques: [
        {
          id: 12,
          technique_id: 'T1059.001',
          tactic_id: 2,
          name: 'PowerShell',
          description: 'Adversaries may abuse PowerShell commands.',
          is_subtechnique: true,
          parent_technique_id: 'T1059',
        },
      ],
    },
  ]

  const mockCoverage: MatrixCoverageResponse = {
    incident_id: 1,
    total_techniques: 35,
    covered_techniques: 1,
    coverage_percentage: 2.8,
    tactics: [
      {
        tactic_id: 'TA0002',
        name: 'Execution',
        display_order: 2,
        mapped_count: 1,
        total_count: 5,
        techniques: [
          {
            id: 12,
            technique_id: 'T1059.001',
            name: 'PowerShell',
            is_subtechnique: true,
            is_mapped: true,
          },
        ],
      },
    ],
  }

  const mockPlaybooks: IncidentPlaybook[] = [
    {
      id: 1,
      playbook_id: 'PB-IR-001',
      title: 'Malware & Ransomware Response Playbook',
      category: 'MALWARE',
      severity_guidance: 'CRITICAL',
      description: 'Standard procedure for rapidly containing ransomware outbreaks.',
      phases_definition: JSON.stringify({
        CONTAINMENT: ['Isolate network VLAN', 'Quarantine host agent'],
      }),
      checklist_json: JSON.stringify(['Collect memory dump', 'Extract C2 IP addresses']),
      recommended_actions_json: JSON.stringify(['SIMULATE_HOST_ISOLATION', 'SIMULATE_IOC_BLOCK']),
      version: '1.0',
      is_active: true,
    },
  ]

  const mockReport: IncidentReport = {
    incident_id: 'INC-2026-0001',
    title: 'PowerShell Memory Injection & Lateral Reconnaissance',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    phase: 'DETECTION_ANALYSIS',
    classification: 'CONFIRMED_INCIDENT',
    lead_analyst: 'SOC Lead Analyst',
    detected_at: '2026-10-01T00:00:00Z',
    tactics_observed: ['Execution', 'Initial Access'],
    techniques_observed: [
      {
        technique_id: 'T1059.001',
        name: 'PowerShell',
        confidence: 'OBSERVED_EVIDENCE',
        evidence: 'Sysmon Event 1',
      },
    ],
    evidence_count: 1,
    evidence_items: [
      {
        evidence_id: 'EVD-ALT-001-A1',
        title: 'Suspicious PowerShell Execution Alert',
        type: 'ALERT',
        source: 'DETECTION',
        hash_sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        relevance: 'SUPPORTING',
      },
    ],
    timeline_entries: [
      {
        timestamp: '2026-10-01T00:01:00Z',
        title: 'Initial Malicious Execution',
        category: 'EXECUTION',
        is_milestone: true,
      },
    ],
    actions_taken: [
      {
        action_id: 'ACT-001',
        type: 'SIMULATE_HOST_ISOLATION',
        category: 'CONTAINMENT',
        target: 'NN-DEV-001',
        status: 'EXECUTED',
      },
    ],
    hypotheses_tested: [
      {
        id: 'HYP-001',
        statement: 'Attacker gained initial access via compromised SSH key.',
        status: 'SUPPORTED',
        confidence: 'HIGH',
      },
    ],
    findings: [
      {
        id: 'FND-001',
        title: 'PowerShell Memory Injection Confirmed',
        severity: 'CRITICAL',
        mitre_technique: 'T1055',
      },
    ],
    markdown_report: '# Executive Incident Report: INC-2026-0001\n\nNIST SP 800-61 Post-Incident Analysis.',
    generated_at: '2026-10-01T01:00:00Z',
  }

  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(incidentResponseApi.listIncidents).mockResolvedValue({
      total: 2,
      skip: 0,
      limit: 20,
      items: mockIncidents,
    })
    vi.mocked(incidentResponseApi.getMetrics).mockResolvedValue(mockMetrics)
    vi.mocked(incidentResponseApi.getIncident).mockResolvedValue(mockIncidents[0])
    vi.mocked(incidentResponseApi.listTactics).mockResolvedValue(mockTactics)
    vi.mocked(incidentResponseApi.listTechniques).mockResolvedValue([
      mockTactics[0].techniques![0],
      mockTactics[1].techniques![0],
    ])
    vi.mocked(incidentResponseApi.getMatrixCoverage).mockResolvedValue(mockCoverage)
    vi.mocked(incidentResponseApi.listPlaybooks).mockResolvedValue(mockPlaybooks)
    vi.mocked(incidentResponseApi.getPlaybook).mockResolvedValue(mockPlaybooks[0])
    vi.mocked(incidentResponseApi.getIncidentReport).mockResolvedValue(mockReport)
  })

  it('renders IncidentsPage with metrics, incident list, filter controls, and safety banner', async () => {
    await act(async () => {
      render(
        <MemoryRouter>
          <IncidentsPage />
        </MemoryRouter>
      )
    })

    expect(screen.getByText(/Security Incident Queue/i)).toBeInTheDocument()
    expect(screen.getByText(/Synthetic Training Environment/i)).toBeInTheDocument()
    expect(screen.getByText(/PowerShell Memory Injection & Lateral Reconnaissance/i)).toBeInTheDocument()
    expect(screen.getByText('INC-2026-0001')).toBeInTheDocument()
    expect(screen.getByText('INC-2026-0002')).toBeInTheDocument()
    expect(screen.getByText('CRITICAL')).toBeInTheDocument()
  })

  it('renders IncidentDetailPage Overview tab with incident metadata, severity, and phase', async () => {
    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/soc/incidents/INC-2026-0001']}>
          <Routes>
            <Route path="/soc/incidents/:incidentId" element={<IncidentDetailPage />} />
          </Routes>
        </MemoryRouter>
      )
    })

    expect(screen.getAllByText('INC-2026-0001').length).toBeGreaterThan(0)
    expect(screen.getByText(/PowerShell Memory Injection & Lateral Reconnaissance/i)).toBeInTheDocument()
    expect(screen.getByText('SOC Lead Analyst')).toBeInTheDocument()
    expect(screen.getByText(/Executive Incident Summary/i)).toBeInTheDocument()
  })

  it('switches between workbench tabs (Timeline, Evidence, MITRE, Simulator, Report)', async () => {
    const user = userEvent.setup()

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/soc/incidents/INC-2026-0001']}>
          <Routes>
            <Route path="/soc/incidents/:incidentId" element={<IncidentDetailPage />} />
          </Routes>
        </MemoryRouter>
      )
    })

    // Click Timeline tab
    const timelineTab = screen.getByRole('tab', { name: /Timeline/i })
    await act(async () => {
      await user.click(timelineTab)
    })
    expect(screen.getByText(/Auto-Sync Sources/i)).toBeInTheDocument()
    expect(screen.getByText(/Initial Malicious Execution/i)).toBeInTheDocument()

    // Click MITRE ATT&CK tab
    const mitreTab = screen.getByRole('tab', { name: /MITRE ATT&CK/i })
    await act(async () => {
      await user.click(mitreTab)
    })
    expect(screen.getByText(/Show Observed Techniques Only/i)).toBeInTheDocument()

    // Click Response Simulation tab
    const simTab = screen.getByRole('tab', { name: /Response Simulation/i })
    await act(async () => {
      await user.click(simTab)
    })
    expect(screen.getByText(/Simulation Mode Only/i)).toBeInTheDocument()

    // Click Executive Report tab
    const reportTab = screen.getByRole('tab', { name: /Executive Report/i })
    await act(async () => {
      await user.click(reportTab)
    })
    expect(screen.getByText(/NIST SP 800-61 Post-Incident Executive Report/i)).toBeInTheDocument()
  })

  it('renders EvidenceDrawer and allows hash verification / inspection', async () => {
    const user = userEvent.setup()

    vi.mocked(incidentResponseApi.verifyEvidenceHash).mockResolvedValue({
      evidence_id: 'EVD-ALT-001-A1',
      stored_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      computed_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      is_valid: true,
      verified_at: '2026-10-01T01:00:00Z',
    })

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/soc/incidents/INC-2026-0001']}>
          <Routes>
            <Route path="/soc/incidents/:incidentId" element={<IncidentDetailPage />} />
          </Routes>
        </MemoryRouter>
      )
    })

    // Switch to Evidence tab
    const evidenceTab = screen.getByRole('tab', { name: /Evidence & Custody/i })
    await act(async () => {
      await user.click(evidenceTab)
    })

    expect(screen.getByText(/\+ Attach Evidence/i)).toBeInTheDocument()
    expect(screen.getByText(/Suspicious PowerShell Execution Alert/i)).toBeInTheDocument()
    expect(screen.getByText('EVD-ALT-001-A1')).toBeInTheDocument()

    // Click Verify Hash button
    const verifyBtn = screen.getByRole('button', { name: /Verify Hash/i })
    await act(async () => {
      await user.click(verifyBtn)
    })
    expect(incidentResponseApi.verifyEvidenceHash).toHaveBeenCalledWith(1, 101)
    expect(screen.getByText(/Cryptographic Hash Matches Stored Value/i)).toBeInTheDocument()
  })

  it('renders ResponseSimulator and allows executing a simulated containment action', async () => {
    const user = userEvent.setup()

    vi.mocked(incidentResponseApi.executeAction).mockResolvedValue({
      ...mockActions[0],
      status: 'EXECUTED',
      executed_at: '2026-10-01T00:36:00Z',
    })

    await act(async () => {
      render(
        <MemoryRouter initialEntries={['/soc/incidents/INC-2026-0001']}>
          <Routes>
            <Route path="/soc/incidents/:incidentId" element={<IncidentDetailPage />} />
          </Routes>
        </MemoryRouter>
      )
    })

    // Switch to Response Simulation tab
    const simTab = screen.getByRole('tab', { name: /Response Simulation/i })
    await act(async () => {
      await user.click(simTab)
    })

    expect(screen.getByText(/Simulation Mode Only/i)).toBeInTheDocument()
    expect(screen.getByText('NN-DEV-001')).toBeInTheDocument()

    // Execute the proposed simulation
    const executeBtn = screen.getByRole('button', { name: /Simulate Action/i })
    await act(async () => {
      await user.click(executeBtn)
    })

    expect(incidentResponseApi.executeAction).toHaveBeenCalledWith(1, 501)
  })

  it('renders MitreCoveragePage and displays the ATT&CK catalog matrix', async () => {
    await act(async () => {
      render(
        <MemoryRouter>
          <MitreCoveragePage />
        </MemoryRouter>
      )
    })

    expect(screen.getByText(/MITRE ATT&CK Enterprise Matrix/i)).toBeInTheDocument()
    expect(screen.getByText(/Execution/i)).toBeInTheDocument()
    expect(screen.getByText('T1059.001')).toBeInTheDocument()
  })

  it('renders PlaybooksPage and displays standard operating procedures', async () => {
    await act(async () => {
      render(
        <MemoryRouter>
          <PlaybooksPage />
        </MemoryRouter>
      )
    })

    expect(screen.getByText(/Standardized Incident Response Playbooks/i)).toBeInTheDocument()
    expect(screen.getAllByText(/Malware & Ransomware Response Playbook/i).length).toBeGreaterThan(0)
    expect(screen.getAllByText('PB-IR-001').length).toBeGreaterThan(0)
  })
})
