from app.models.enums import CognitiveLevel, DifficultyLevel, QuestionType

TAGS_DATA = [
    {"name": "OSI Model", "slug": "osi"},
    {"name": "TCP", "slug": "tcp"},
    {"name": "UDP", "slug": "udp"},
    {"name": "DNS", "slug": "dns"},
    {"name": "Subnetting", "slug": "subnetting"},
    {"name": "Routing", "slug": "routing"},
    {"name": "Switching", "slug": "switching"},
    {"name": "Security", "slug": "security"},
    {"name": "Troubleshooting", "slug": "troubleshooting"},
    {"name": "Packet Analysis", "slug": "packet-analysis"},
    {"name": "IPv4", "slug": "ipv4"},
    {"name": "IPv6", "slug": "ipv6"},
    {"name": "Firewall", "slug": "firewall"},
    {"name": "IDS/IPS", "slug": "ids-ips"},
    {"name": "ARP", "slug": "arp"},
]

SAMPLE_QUESTIONS = [
    # 0. Single Choice — Beginner — OSI Model
    {
        "topic_slug": "seven-osi-layers",
        "question_text": "Which OSI layer is directly responsible for end-to-end flow control, error checking, and port addressing?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "Layer 4 (Transport Layer) manages end-to-end communication, port-level multiplexing, flow control, and data reliability (RFC 793).",
        "learning_objective": "Identify the primary responsibility and protocols of OSI Layer 4.",
        "tags": ["osi", "tcp", "udp"],
        "options": [
            {"option_text": "Network Layer (Layer 3)", "is_correct": False, "order_index": 1},
            {"option_text": "Transport Layer (Layer 4)", "is_correct": True, "order_index": 2},
            {"option_text": "Data Link Layer (Layer 2)", "is_correct": False, "order_index": 3},
            {"option_text": "Session Layer (Layer 5)", "is_correct": False, "order_index": 4},
        ],
    },
    # 1. Multiple Choice — Beginner — Basic Addressing
    {
        "topic_slug": "public-vs-private-ip",
        "question_text": "Which of the following IPv4 address blocks are defined by RFC 1918 as non-routable private addresses? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "RFC 1918 defines three private ranges: 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. Range 169.254.0.0/16 is APIPA/Link-Local (RFC 3927) and 100.64.0.0/10 is Carrier-Grade NAT (RFC 6598).",
        "learning_objective": "Differentiate RFC 1918 private IPv4 subnets from routable public and link-local addresses.",
        "tags": ["ipv4", "subnetting"],
        "options": [
            {"option_text": "10.0.0.0/8 (10.0.0.0 - 10.255.255.255)", "is_correct": True, "order_index": 1},
            {"option_text": "172.16.0.0/12 (172.16.0.0 - 172.31.255.255)", "is_correct": True, "order_index": 2},
            {"option_text": "169.254.0.0/16", "is_correct": False, "order_index": 3},
            {"option_text": "192.168.0.0/16 (192.168.0.0 - 192.168.255.255)", "is_correct": True, "order_index": 4},
        ],
    },
    # 2. Single Choice — Intermediate — Subnetting
    {
        "topic_slug": "subnetting",
        "question_text": "How many usable host IP addresses are available in the IPv4 subnet 192.168.10.0/27?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.APPLY,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "A /27 subnet leaves 32 - 27 = 5 host bits. Total addresses = 2^5 = 32. Subtracting network (1) and broadcast (1) addresses leaves 32 - 2 = 30 usable host IP addresses.",
        "learning_objective": "Calculate usable host counts using IPv4 CIDR prefix notation.",
        "tags": ["ipv4", "subnetting"],
        "options": [
            {"option_text": "28 usable hosts", "is_correct": False, "order_index": 1},
            {"option_text": "30 usable hosts", "is_correct": True, "order_index": 2},
            {"option_text": "32 usable hosts", "is_correct": False, "order_index": 3},
            {"option_text": "62 usable hosts", "is_correct": False, "order_index": 4},
        ],
    },
    # 3. Single Choice — Intermediate — TCP Handshake
    {
        "topic_slug": "tcp-three-way-handshake",
        "question_text": "During standard TCP three-way handshake establishment, which packet is sent by the server in response to an initial SYN packet from the client?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "The server acknowledges the client's SYN sequence number and sends its own initial sequence number via a SYN-ACK packet.",
        "learning_objective": "Understand state transitions and message sequence in TCP connection establishment.",
        "tags": ["tcp"],
        "options": [
            {"option_text": "ACK", "is_correct": False, "order_index": 1},
            {"option_text": "SYN-ACK", "is_correct": True, "order_index": 2},
            {"option_text": "RST", "is_correct": False, "order_index": 3},
            {"option_text": "PSH-ACK", "is_correct": False, "order_index": 4},
        ],
    },
    # 4. Single Choice — Intermediate — Switching
    {
        "topic_slug": "mac-address-table",
        "question_text": "When an Ethernet switch receives a unicast frame whose destination MAC address does not exist in its CAM/MAC table, how does the switch handle the frame?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "This behavior is known as Unknown Unicast Flooding. The switch forwards the frame out all ports in the same VLAN except the ingress port.",
        "learning_objective": "Explain Layer 2 frame forwarding, learning, and unknown unicast flooding mechanisms.",
        "tags": ["switching"],
        "options": [
            {"option_text": "Drops the frame silently", "is_correct": False, "order_index": 1},
            {"option_text": "Floods the frame out of all ports within the VLAN except the ingress port", "is_correct": True, "order_index": 2},
            {"option_text": "Sends an ICMP Host Unreachable message back to the source", "is_correct": False, "order_index": 3},
            {"option_text": "Buffers the frame until an ARP broadcast is completed", "is_correct": False, "order_index": 4},
        ],
    },
    # 5. True/False — Beginner — ARP
    {
        "topic_slug": "arp",
        "question_text": "The Address Resolution Protocol (ARP) resolves known Layer 3 IP addresses to corresponding Layer 2 MAC addresses on a local subnet.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. ARP (RFC 826) broadcasts requests on the local link asking 'Who has this IP? Tell my MAC address', resolving IP to physical Layer 2 MAC addresses.",
        "learning_objective": "Understand the core mapping purpose of Address Resolution Protocol.",
        "tags": ["arp", "osi"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 6. Multiple Choice — Beginner — Ports
    {
        "topic_slug": "ports",
        "question_text": "Which of the following transport layer port numbers match their default standard protocols? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "DNS uses UDP/TCP port 53; HTTPS uses TCP port 443; SSH uses TCP port 22. Port 80 is used by unencrypted HTTP, while SNMP typically uses UDP port 161.",
        "learning_objective": "Identify standard well-known IANA port numbers and associated application layer services.",
        "tags": ["ports", "dns", "tcp", "udp"],
        "options": [
            {"option_text": "DNS — Port 53", "is_correct": True, "order_index": 1},
            {"option_text": "HTTPS — Port 443", "is_correct": True, "order_index": 2},
            {"option_text": "SSH — Port 22", "is_correct": True, "order_index": 3},
            {"option_text": "HTTP — Port 21", "is_correct": False, "order_index": 4},
        ],
    },
    # 7. Multiple Choice — Beginner — UDP vs TCP
    {
        "topic_slug": "tcp-vs-udp",
        "question_text": "Which characteristics distinguish UDP (User Datagram Protocol) from TCP? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "UDP provides connectionless, best-effort datagram delivery with minimal header overhead (8 bytes) and no retransmissions. In contrast, TCP provides sequenced, reliable delivery with 3-way handshakes and acknowledgments.",
        "learning_objective": "Contrast connection-oriented TCP against lightweight connectionless UDP.",
        "tags": ["tcp", "udp"],
        "options": [
            {"option_text": "UDP is connectionless and does not perform a 3-way handshake", "is_correct": True, "order_index": 1},
            {"option_text": "UDP has a lower header overhead (8 bytes) compared to TCP (20+ bytes)", "is_correct": True, "order_index": 2},
            {"option_text": "UDP guarantees packet ordering using sequence numbers", "is_correct": False, "order_index": 3},
            {"option_text": "UDP automatically retransmits corrupted segments", "is_correct": False, "order_index": 4},
        ],
    },
    # 8. Multiple Choice — Intermediate — Stateful Firewalls
    {
        "topic_slug": "stateful-vs-stateless-filtering",
        "question_text": "What advantages does a stateful inspection firewall offer over a traditional stateless packet-filtering firewall? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.ANALYZE,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "Stateful firewalls maintain connection tracking state tables to dynamically inspect packet sequences and permit returning response traffic without requiring static inbound ports.",
        "learning_objective": "Contrast stateful session tracking with static rule matching.",
        "tags": ["firewall", "security"],
        "options": [
            {"option_text": "Tracks TCP connection states (SYN_SENT, ESTABLISHED, FIN_WAIT)", "is_correct": True, "order_index": 1},
            {"option_text": "Dynamically allows returning traffic for outbound client sessions", "is_correct": True, "order_index": 2},
            {"option_text": "Filters traffic purely based on isolated packet headers without memory", "is_correct": False, "order_index": 3},
            {"option_text": "Protects against out-of-sequence TCP packets and ACK scanning", "is_correct": True, "order_index": 4},
        ],
    },
    # 9. Single Choice — Advanced — Detection Rules
    {
        "topic_slug": "detection-rules",
        "question_text": "A security analyst notices repeated ICMP Echo Request packets with unusually large 1400-byte payloads containing base64 strings. What technique is most likely occurring?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.ADVANCED,
        "cognitive_level": CognitiveLevel.ANALYZE,
        "points": 3,
        "estimated_seconds": 90,
        "explanation": "ICMP Tunneling / Exfiltration embeds arbitrary data into the optional data payload field of ICMP Echo packets to bypass perimeter firewalls that permit outbound ping.",
        "learning_objective": "Identify covert channels and protocol tunneling attacks in network traffic.",
        "tags": ["security", "packet-analysis", "ids-ips"],
        "options": [
            {"option_text": "Path MTU Discovery (RFC 1191)", "is_correct": False, "order_index": 1},
            {"option_text": "ICMP Data Exfiltration / Covert Tunneling", "is_correct": True, "order_index": 2},
            {"option_text": "Normal IPv6 Router Advertisement", "is_correct": False, "order_index": 3},
            {"option_text": "BGP Keepalive beaconing", "is_correct": False, "order_index": 4},
        ],
    },
    # 10. Single Choice — Beginner — LAN & Default Gateway
    {
        "topic_slug": "lan",
        "question_text": "What is the primary role of a default gateway on a local area network (LAN)?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "The default gateway is the local router interface that routes packets destined for remote networks outside the local subnet.",
        "learning_objective": "Understand the default gateway routing boundary between local subnets and external networks.",
        "tags": ["routing", "ipv4"],
        "options": [
            {"option_text": "Assigns dynamic IP addresses to endpoints via DHCP", "is_correct": False, "order_index": 1},
            {"option_text": "Forwards traffic from local hosts to destinations outside the local subnet", "is_correct": True, "order_index": 2},
            {"option_text": "Resolves domain names to IP addresses", "is_correct": False, "order_index": 3},
            {"option_text": "Synchronizes network clock time using NTP", "is_correct": False, "order_index": 4},
        ],
    },
    # 11. True/False — Beginner — Network Topologies
    {
        "topic_slug": "network-topologies",
        "question_text": "In a Star network topology, the failure of the central switch or hub disconnects all connected devices from network communication.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. The central device in a star topology represents a single point of failure (SPOF); if it fails, all connected peripheral nodes lose network connectivity.",
        "learning_objective": "Identify failure modes and topology dependencies in star architectures.",
        "tags": ["switching", "troubleshooting"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 12. Single Choice — Beginner — DNS
    {
        "topic_slug": "dns",
        "question_text": "Which component of the DNS resolution architecture first accepts queries from end-user client devices and iteratively queries root, TLD, and authoritative nameservers?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "The Recursive Resolver (or DNS Recurser) receives the client's stub query and performs full iterative resolution across root, TLD, and authoritative nameservers on behalf of the client.",
        "learning_objective": "Describe hierarchical DNS resolution and the role of recursive resolvers.",
        "tags": ["dns"],
        "options": [
            {"option_text": "Authoritative Nameserver", "is_correct": False, "order_index": 1},
            {"option_text": "Recursive Resolver", "is_correct": True, "order_index": 2},
            {"option_text": "TLD Nameserver", "is_correct": False, "order_index": 3},
            {"option_text": "Root Nameserver", "is_correct": False, "order_index": 4},
        ],
    },
    # 13. Single Choice — Beginner — Subnet Masks
    {
        "topic_slug": "subnet-masks",
        "question_text": "What is the dotted-decimal subnet mask representation for the CIDR notation /24?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "A /24 prefix represents 24 contiguous binary ones (11111111.11111111.11111111.00000000), which translates to 255.255.255.0.",
        "learning_objective": "Convert between CIDR prefix lengths and dotted-decimal subnet masks.",
        "tags": ["ipv4", "subnetting"],
        "options": [
            {"option_text": "255.255.0.0", "is_correct": False, "order_index": 1},
            {"option_text": "255.255.255.0", "is_correct": True, "order_index": 2},
            {"option_text": "255.255.255.128", "is_correct": False, "order_index": 3},
            {"option_text": "255.255.254.0", "is_correct": False, "order_index": 4},
        ],
    },
    # 14. True/False — Beginner — IPv4 Loopback
    {
        "topic_slug": "ipv4-basics",
        "question_text": "The IPv4 address 127.0.0.1 is reserved as a loopback address to allow a host to send network traffic to itself without accessing a physical network interface.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. The 127.0.0.0/8 block is reserved for loopback testing (RFC 1122), with 127.0.0.1 being the standard localhost address.",
        "learning_objective": "Recognize special IPv4 address blocks including loopback.",
        "tags": ["ipv4"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 15. True/False — Beginner — OSI Protocol Data Units
    {
        "topic_slug": "seven-osi-layers",
        "question_text": "At OSI Layer 2 (Data Link Layer), the Protocol Data Unit (PDU) is known as a 'Frame'.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. Layer 2 PDUs are called Frames, Layer 3 PDUs are Packets, Layer 4 PDUs are Segments (TCP) or Datagrams (UDP), and Layer 1 PDUs are Bits.",
        "learning_objective": "Identify Protocol Data Unit (PDU) nomenclature across OSI layers.",
        "tags": ["osi"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 16. Multiple Choice — Beginner — Common UDP Applications
    {
        "topic_slug": "udp-basics",
        "question_text": "Which of the following networking protocols commonly operate over UDP? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "DNS (port 53 queries), DHCP (ports 67/68), and TFTP (port 69) rely on UDP due to lightweight requirements or broadcast boot constraints. SSH requires reliable TCP (port 22).",
        "learning_objective": "Identify services that choose UDP transport over TCP.",
        "tags": ["udp", "ports"],
        "options": [
            {"option_text": "DNS (Standard query lookups)", "is_correct": True, "order_index": 1},
            {"option_text": "DHCP (Dynamic Host Configuration Protocol)", "is_correct": True, "order_index": 2},
            {"option_text": "TFTP (Trivial File Transfer Protocol)", "is_correct": True, "order_index": 3},
            {"option_text": "SSH (Secure Shell)", "is_correct": False, "order_index": 4},
        ],
    },
    # 17. Single Choice — Beginner — Subnet Broadcast Address
    {
        "topic_slug": "broadcast-address",
        "question_text": "What is the directed broadcast address for the network 192.168.1.0/24?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.APPLY,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "In a /24 subnet, the last address with all host bits set to 1 is the broadcast address: 192.168.1.255.",
        "learning_objective": "Calculate network and broadcast addresses for Class C subnets.",
        "tags": ["ipv4", "subnetting"],
        "options": [
            {"option_text": "192.168.1.0", "is_correct": False, "order_index": 1},
            {"option_text": "192.168.1.254", "is_correct": False, "order_index": 2},
            {"option_text": "192.168.1.255", "is_correct": True, "order_index": 3},
            {"option_text": "192.168.2.0", "is_correct": False, "order_index": 4},
        ],
    },
    # 18. True/False — Beginner — WAN Scope
    {
        "topic_slug": "wan",
        "question_text": "A Wide Area Network (WAN) connects local networks across broad geographical areas and typically relies on service providers or telecommunications carriers.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. WANs span cities, countries, or global links via leased lines, MPLS, or Internet backbones managed by telecommunication service providers.",
        "learning_objective": "Distinguish WAN geographic scope from local campus LANs.",
        "tags": ["routing"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 19. Single Choice — Beginner — MAC Address
    {
        "topic_slug": "mac-address",
        "question_text": "What is the standard length in bits and hexadecimal notation of an Ethernet MAC address?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "A MAC-48 / EUI-48 address is 48 bits (6 bytes / octets) formatted as 12 hexadecimal digits (e.g., 00:1A:2B:3C:4D:5E).",
        "learning_objective": "Identify physical MAC address structure and bit length.",
        "tags": ["switching"],
        "options": [
            {"option_text": "32 bits (4 octets)", "is_correct": False, "order_index": 1},
            {"option_text": "48 bits (6 octets)", "is_correct": True, "order_index": 2},
            {"option_text": "64 bits (8 octets)", "is_correct": False, "order_index": 3},
            {"option_text": "128 bits (16 octets)", "is_correct": False, "order_index": 4},
        ],
    },
    # 20. Multiple Choice — Intermediate — TCP Teardown
    {
        "topic_slug": "tcp-connection-termination",
        "question_text": "Which TCP control flags are used during a standard, graceful four-way connection teardown? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "Graceful termination uses FIN (Finish) and ACK (Acknowledgment) packets exchanged symmetrically by both sides (FIN -> ACK, FIN -> ACK).",
        "learning_objective": "Identify control flags involved in standard TCP connection teardown.",
        "tags": ["tcp"],
        "options": [
            {"option_text": "FIN (Finish)", "is_correct": True, "order_index": 1},
            {"option_text": "ACK (Acknowledgment)", "is_correct": True, "order_index": 2},
            {"option_text": "RST (Reset)", "is_correct": False, "order_index": 3},
            {"option_text": "SYN (Synchronize)", "is_correct": False, "order_index": 4},
        ],
    },
    # 21. Single Choice — Beginner — SSH Port
    {
        "topic_slug": "ssh",
        "question_text": "What is the standard IANA default TCP port used by SSH (Secure Shell) for secure administrative remote console access?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "SSH operates over TCP port 22 by default, providing encrypted terminal and tunneling sessions.",
        "learning_objective": "Recognize essential ports used for secure administration.",
        "tags": ["ports", "security"],
        "options": [
            {"option_text": "Port 21", "is_correct": False, "order_index": 1},
            {"option_text": "Port 22", "is_correct": True, "order_index": 2},
            {"option_text": "Port 23", "is_correct": False, "order_index": 3},
            {"option_text": "Port 25", "is_correct": False, "order_index": 4},
        ],
    },
    # 22. True/False — Beginner — Client-Server
    {
        "topic_slug": "client-server",
        "question_text": "In a Client-Server network architecture, dedicated server hosts manage central resources and answer service requests initiated by client devices.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. In client-server models, clients initiate requests and centralized servers host, process, and respond with network services.",
        "learning_objective": "Define architectural roles in client-server paradigms.",
        "tags": ["troubleshooting"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 23. True/False — Beginner — Peer-to-Peer
    {
        "topic_slug": "peer-to-peer",
        "question_text": "In a true Peer-to-Peer (P2P) network, every node can act as both a client requesting data and a server sharing data.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. P2P architectures distribute workloads across peers symmetrically without requiring a central authority or dedicated server.",
        "learning_objective": "Understand decentralized peer-to-peer characteristics.",
        "tags": ["troubleshooting"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 24. Single Choice — Intermediate — Wireshark Filters
    {
        "topic_slug": "wireshark-filtering-concepts",
        "question_text": "Which Wireshark display filter correctly isolates traffic where the TCP destination or source port is 80?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.APPLY,
        "points": 2,
        "estimated_seconds": 45,
        "explanation": "In Wireshark display filter syntax, 'tcp.port == 80' evaluates both tcp.srcport and tcp.dstport. 'port 80' is Berkeley Packet Filter (BPF) capture filter syntax, not a display filter.",
        "learning_objective": "Formulate valid Wireshark display filters for transport layer ports.",
        "tags": ["packet-analysis"],
        "options": [
            {"option_text": "port 80", "is_correct": False, "order_index": 1},
            {"option_text": "tcp.port == 80", "is_correct": True, "order_index": 2},
            {"option_text": "ip.port == 80", "is_correct": False, "order_index": 3},
            {"option_text": "traffic.port = 80", "is_correct": False, "order_index": 4},
        ],
    },
    # 25. Multiple Choice — Beginner — Mesh Topology
    {
        "topic_slug": "network-topologies",
        "question_text": "Which of the following statements are TRUE regarding a Full Mesh network topology? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "A full mesh connects every node to every other node, providing high fault tolerance and redundant paths, but requires n*(n-1)/2 links, resulting in high cabling complexity and expense.",
        "learning_objective": "Analyze trade-offs between redundancy and cost in mesh topologies.",
        "tags": ["troubleshooting"],
        "options": [
            {"option_text": "Provides the highest level of fault tolerance and redundancy", "is_correct": True, "order_index": 1},
            {"option_text": "Requires n*(n-1)/2 physical links for n devices, increasing cabling cost", "is_correct": True, "order_index": 2},
            {"option_text": "If any single node fails, the entire network immediately collapses", "is_correct": False, "order_index": 3},
            {"option_text": "Every device has a dedicated point-to-point link to every other device", "is_correct": True, "order_index": 4},
        ],
    },
    # 26. True/False — Beginner — Layer 3 PDU
    {
        "topic_slug": "tcp-ip-layers",
        "question_text": "At the Network (Internet) layer, the Protocol Data Unit (PDU) that contains IP source and destination addresses is termed a 'Packet'.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. Layer 3 encapsulates transport segments into Packets by prepending the IP header.",
        "learning_objective": "Recognize Layer 3 encapsulation PDU terminology.",
        "tags": ["osi", "ipv4"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 27. Single Choice — Beginner — IPv4 Size
    {
        "topic_slug": "ipv4-address-structure",
        "question_text": "How many total bits constitute an IPv4 address, and how are they conventionally partitioned?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "An IPv4 address contains 32 bits divided into 4 octets of 8 bits each, represented in dotted-decimal format.",
        "learning_objective": "Recall IPv4 address length and octet structure.",
        "tags": ["ipv4"],
        "options": [
            {"option_text": "32 bits divided into 4 octets", "is_correct": True, "order_index": 1},
            {"option_text": "64 bits divided into 8 octets", "is_correct": False, "order_index": 2},
            {"option_text": "128 bits divided into 8 hextets", "is_correct": False, "order_index": 3},
            {"option_text": "48 bits divided into 6 octets", "is_correct": False, "order_index": 4},
        ],
    },
    # 28. Single Choice — Intermediate — /28 Subnet Usable Hosts
    {
        "topic_slug": "subnetting",
        "question_text": "A network engineer provisions a subnet with prefix /28. How many usable host IP addresses does this subnet accommodate?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.APPLY,
        "points": 2,
        "estimated_seconds": 45,
        "explanation": "32 - 28 = 4 host bits. Total addresses = 2^4 = 16. Usable addresses = 16 - 2 = 14.",
        "learning_objective": "Calculate usable hosts in small CIDR subnets.",
        "tags": ["ipv4", "subnetting"],
        "options": [
            {"option_text": "6 usable hosts", "is_correct": False, "order_index": 1},
            {"option_text": "14 usable hosts", "is_correct": True, "order_index": 2},
            {"option_text": "16 usable hosts", "is_correct": False, "order_index": 3},
            {"option_text": "30 usable hosts", "is_correct": False, "order_index": 4},
        ],
    },
    # 29. Single Choice — Beginner — Firewall Default Posture
    {
        "topic_slug": "firewall-basics",
        "question_text": "What is the recommended defensive security baseline for firewall rule configuration?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "Default Deny (Implicit Deny) blocks all ingress and egress traffic by default unless an explicit permit rule matches, adhering to the principle of least privilege.",
        "learning_objective": "Understand the principle of default deny in network access control.",
        "tags": ["firewall", "security"],
        "options": [
            {"option_text": "Default Permit (Allow all traffic unless specifically blocked)", "is_correct": False, "order_index": 1},
            {"option_text": "Default Deny / Implicit Deny (Block all traffic unless explicitly permitted)", "is_correct": True, "order_index": 2},
            {"option_text": "Permit all internal LAN traffic to bypass inspection unconditionally", "is_correct": False, "order_index": 3},
            {"option_text": "Rely solely on router interface speed throttling", "is_correct": False, "order_index": 4},
        ],
    },
    # 30. Single Choice — Intermediate — TCP Window Size
    {
        "topic_slug": "tcp-flags",
        "question_text": "What is the primary function of the Window Size field in a TCP header?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "TCP Window Size enables flow control by advertising the number of bytes the receiving host's buffer can accept before requiring an acknowledgment.",
        "learning_objective": "Explain TCP flow control and sliding window mechanics.",
        "tags": ["tcp"],
        "options": [
            {"option_text": "Identifies the application protocol (e.g., HTTP or SSH)", "is_correct": False, "order_index": 1},
            {"option_text": "Controls flow by indicating how many bytes the receiver can accept", "is_correct": True, "order_index": 2},
            {"option_text": "Enforces packet encryption keys", "is_correct": False, "order_index": 3},
            {"option_text": "Measures round-trip latency to the gateway", "is_correct": False, "order_index": 4},
        ],
    },
    # 31. Single Choice — Beginner — DNS Root
    {
        "topic_slug": "dns",
        "question_text": "In hierarchical DNS resolution, what is the role of Root Nameservers (represented by a dot '.')?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 1,
        "estimated_seconds": 45,
        "explanation": "Root nameservers sit at the top of the DNS hierarchy and direct recursive resolvers to the appropriate Top-Level Domain (TLD) nameservers (such as .com, .org, .net).",
        "learning_objective": "Describe root nameserver functionality in DNS hierarchy.",
        "tags": ["dns"],
        "options": [
            {"option_text": "Store final IP addresses for all registered websites worldwide", "is_correct": False, "order_index": 1},
            {"option_text": "Direct resolvers to the authoritative Top-Level Domain (TLD) servers", "is_correct": True, "order_index": 2},
            {"option_text": "Filter malicious URLs before web browsers can open them", "is_correct": False, "order_index": 3},
            {"option_text": "Assign dynamic IP addresses to clients on boot", "is_correct": False, "order_index": 4},
        ],
    },
    # 32. True/False — Intermediate — ARP Poisoning
    {
        "topic_slug": "arp",
        "question_text": "ARP spoofing / cache poisoning attacks are possible because traditional ARP messages have no built-in cryptographic authentication mechanism.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 45,
        "explanation": "True. Standard ARP (RFC 826) accepts unsolicited gratuitous ARP replies without verifying identity, allowing attackers on the local subnet to poison ARP tables and perform Man-in-the-Middle (MitM) attacks.",
        "learning_objective": "Identify cryptographic weaknesses in ARP and implications for local network attacks.",
        "tags": ["arp", "security"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 33. Multiple Choice — Intermediate — Wireshark Capture vs Display Filters
    {
        "topic_slug": "wireshark-filtering-concepts",
        "question_text": "How do Wireshark capture filters differ from display filters? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.ANALYZE,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "Capture filters use libpcap/BPF syntax and discard non-matching packets before disk storage. Display filters are applied post-capture to the loaded packet buffer and can be changed non-destructively at any time.",
        "learning_objective": "Distinguish pre-capture BPF filtering from post-capture display filtering in Wireshark.",
        "tags": ["packet-analysis"],
        "options": [
            {"option_text": "Capture filters use Berkeley Packet Filter (BPF) syntax (e.g. 'host 10.0.0.1')", "is_correct": True, "order_index": 1},
            {"option_text": "Capture filters discard non-matching packets before they are saved to disk", "is_correct": True, "order_index": 2},
            {"option_text": "Display filters alter what is visible without deleting packet data from the capture file", "is_correct": True, "order_index": 3},
            {"option_text": "Display filters cannot filter by protocol names", "is_correct": False, "order_index": 4},
        ],
    },
    # 34. Single Choice — Intermediate — Point-to-Point /30 Subnet
    {
        "topic_slug": "subnetting",
        "question_text": "Why was a /30 subnet historically the standard choice for point-to-point router links in IPv4 networks?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.APPLY,
        "points": 2,
        "estimated_seconds": 45,
        "explanation": "A /30 prefix provides 4 total IP addresses: 1 network, 1 broadcast, and exactly 2 usable host addresses, perfectly fitting two interconnected router interfaces without wasting address space.",
        "learning_objective": "Understand point-to-point link sizing and address conservation.",
        "tags": ["ipv4", "subnetting", "routing"],
        "options": [
            {"option_text": "It provides 6 usable host addresses for redundancy", "is_correct": False, "order_index": 1},
            {"option_text": "It provides exactly 2 usable host addresses for the two endpoints", "is_correct": True, "order_index": 2},
            {"option_text": "It eliminates the need for an ARP table", "is_correct": False, "order_index": 3},
            {"option_text": "It automatically encrypts traffic across the link", "is_correct": False, "order_index": 4},
        ],
    },
    # 35. True/False — Beginner — Network Purpose
    {
        "topic_slug": "what-is-computer-networking",
        "question_text": "The primary objective of computer networking is enabling distributed computing nodes to share resources, transfer data, and communicate reliably.",
        "question_type": QuestionType.TRUE_FALSE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "True. Computer networks connect autonomous computing systems to facilitate resource sharing, data transfer, and communication.",
        "learning_objective": "Recognize fundamental goals of distributed computer networking.",
        "tags": ["troubleshooting"],
        "options": [
            {"option_text": "True", "is_correct": True, "order_index": 1},
            {"option_text": "False", "is_correct": False, "order_index": 2},
        ],
    },
    # 36. Multiple Choice — Beginner — Insecure Legacy Protocols
    {
        "topic_slug": "ports",
        "question_text": "Which of the following legacy protocols transmit authentication credentials and payload data in unencrypted plaintext? (Select all that apply)",
        "question_type": QuestionType.MULTIPLE_CHOICE,
        "difficulty": DifficultyLevel.BEGINNER,
        "cognitive_level": CognitiveLevel.UNDERSTAND,
        "points": 2,
        "estimated_seconds": 60,
        "explanation": "Telnet (port 23), HTTP (port 80), and FTP (port 21) transmit cleartext data vulnerable to packet sniffing. In contrast, HTTPS (port 443) and SSH (port 22) use TLS/SSH cryptographic encryption.",
        "learning_objective": "Identify cleartext protocols and modern encrypted alternatives.",
        "tags": ["security", "ports"],
        "options": [
            {"option_text": "Telnet (Port 23)", "is_correct": True, "order_index": 1},
            {"option_text": "HTTP (Port 80)", "is_correct": True, "order_index": 2},
            {"option_text": "FTP (Port 21)", "is_correct": True, "order_index": 3},
            {"option_text": "HTTPS (Port 443)", "is_correct": False, "order_index": 4},
        ],
    },
    # 37. Single Choice — Intermediate — Default Route
    {
        "topic_slug": "default-routes",
        "question_text": "How is a default route represented in IPv4 routing tables using CIDR notation?",
        "question_type": QuestionType.SINGLE_CHOICE,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "cognitive_level": CognitiveLevel.REMEMBER,
        "points": 1,
        "estimated_seconds": 30,
        "explanation": "0.0.0.0/0 (the quad-zero route) matches any destination address when no more-specific route exists in the routing table.",
        "learning_objective": "Identify default static route notation in routing tables.",
        "tags": ["routing", "ipv4"],
        "options": [
            {"option_text": "127.0.0.1/32", "is_correct": False, "order_index": 1},
            {"option_text": "0.0.0.0/0", "is_correct": True, "order_index": 2},
            {"option_text": "255.255.255.255/32", "is_correct": False, "order_index": 3},
            {"option_text": "192.168.0.0/16", "is_correct": False, "order_index": 4},
        ],
    },
]
